# System

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[env]
PAGER = "less"
EDITOR = "nvim"
JAVA_HOME = "/usr/lib/jvm/default-java/"

# Colors (Blood Moon)
[font]
size = 12

[font.normal]
family = "SauceCodePro NFM"
style  = "Regular"

[font.bold]
family = "SauceCodePro NFM"
style  = "Bold"

[font.italic]
family = "SauceCodePro NFM"
style  = "Italic"

[window]
opacity = 0.85

[colors.primary]
background = '#10100E'
foreground = '#C6C6C4'

[colors.normal]
black   = '#10FF0E'
red     = '#C40233'
green   = '#009F6B'
yellow  = '#FFD700'
blue    = '#0087BD'
magenta = '#9A4EAE'
cyan    = '#20B2AA'
white   = '#C6C6C4'

[colors.bright]
black   = '#696969'
red     = '#FF2400'
green   = '#03C03C'
yellow  = '#FDFF00'
blue    = '#007FFF'
magenta = '#FF1493'
cyan    = '#00CCCC'
white   = '#FFFAFA'
